from app import db

class RawGasStream(db.Document):
    producer_name = db.StringField()
    processor_name = db.StringField()
    settlement_month = db.IntField()
    settlement_year = db.IntField()
    methane_mole_fraction = db.FloatField()
    ethane_mole_fraction = db.FloatField()
    propane_mole_fraction = db.FloatField()
    n_butane_mole_fraction = db.FloatField()
    i_butane_mole_fraction = db.FloatField()
    n_pentane_mole_fraction = db.FloatField()
    i_pentane_mole_fraction = db.FloatField()
    hexane_plus_mole_fraction = db.FloatField()
    carbon_dioxide_mole_fraction = db.FloatField()
    hydrogen_sulfide_mole_fraction = db.FloatField()
    nitrogen_mole_fraction = db.FloatField()
    oxygen_mole_fraction = db.FloatField()
    helium_mole_fraction = db.FloatField()
    methane_recovery_factor = db.FloatField()
    ethane_recovery_factor = db.FloatField()
    propane_recovery_factor = db.FloatField()
    n_butane_recovery_factor = db.FloatField()
    i_butane_recovery_factor = db.FloatField()
    n_pentane_recovery_factor = db.FloatField()
    i_pentane_recovery_factor = db.FloatField()
    hexane_plus_recovery_factor = db.FloatField()
    carbon_dioxide_recovery_factor = db.FloatField()
    hydrogen_sulfide_recovery_factor = db.FloatField()
    nitrogen_recovery_factor = db.FloatField()
    oxygen_recovery_factor = db.FloatField()
    helium_recovery_factor = db.FloatField()
    methane_price = db.FloatField()
    ethane_price = db.FloatField()
    propane_price = db.FloatField()
    n_butane_price = db.FloatField()
    i_butane_price = db.FloatField()
    n_pentane_price = db.FloatField()
    i_pentane_price = db.FloatField()
    hexane_plus_price = db.FloatField()
    carbon_dioxide_price = db.FloatField()
    hydrogen_sulfide_price = db.FloatField()
    nitrogen_price = db.FloatField()
    oxygen_price = db.FloatField()
    helium_price = db.FloatField()
    temperature = db.FloatField()
    pressure = db.FloatField()
    volume = db.FloatField()
    timestamp = db.DateTimeField()

    meta = {
        'indexes': [('producer_name', 'processor_name', 'settlement_month', 'settlement_year')]
    }


class FractionatedStream(db.Document):
    producer_name = db.StringField()
    processor_name = db.StringField()
    settlement_month = db.IntField()
    settlement_year = db.IntField()
    gas_volume = db.FloatField()
    gas_energy = db.FloatField()
    real_gas_heating_value = db.FloatField()
    compressibility_factor = db.FloatField()
    ethane_recovered_volume = db.FloatField()
    ethane_shrink_energy = db.FloatField()
    ethane_value = db.FloatField()
    propane_recovered_volume = db.FloatField()
    propane_shrink_energy = db.FloatField()
    propane_value = db.FloatField()
    i_butane_recovered_volume = db.FloatField()
    i_butane_shrink_energy = db.FloatField()
    i_butane_value = db.FloatField()
    n_butane_recovered_volume = db.FloatField()
    n_butane_shrink_energy = db.FloatField()
    n_butane_value = db.FloatField()
    i_pentane_recovered_volume = db.FloatField()
    i_pentane_shrink_energy = db.FloatField()
    i_pentane_value = db.FloatField()
    n_pentane_recovered_volume = db.FloatField()
    n_pentane_shrink_energy = db.FloatField()
    n_pentane_value = db.FloatField()
    hexane_plus_recovered_volume = db.FloatField()
    hexane_plus_shrink_energy = db.FloatField()
    hexane_plus_value = db.FloatField()
    residue_real_gas_heating_value = db.FloatField()
    residue_gas_compressibility_factor = db.FloatField()
    residue_gas_volume = db.FloatField()
    residue_gas_energy = db.FloatField()
    residue_gas_value = db.FloatField()

    meta = {
        'indexes': [('producer_name', 'processor_name', 'settlement_month', 'settlement_year')]
    }
