version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /home/tomortiz/projects/pygasfrac:/pygasfrac
    links:
      - db:mongodb
    container_name: pygasfrac_web_1
    depends_on:
      - db
  db:
    image: mongo:3.6.8
    container_name: pygasfrac_db_1